/** Nomes em pt-BR para selecoes vindas da football-data.org. */
const TEAM_NAMES_PT_BR: Record<string, string> = {
  Brazil: "Brasil",
  Argentina: "Argentina",
  Uruguay: "Uruguai",
  Colombia: "Colômbia",
  Chile: "Chile",
  Peru: "Peru",
  Ecuador: "Equador",
  Paraguay: "Paraguai",
  Bolivia: "Bolívia",
  Venezuela: "Venezuela",
  Mexico: "México",
  "United States": "Estados Unidos",
  USA: "Estados Unidos",
  Canada: "Canadá",
  "Costa Rica": "Costa Rica",
  Panama: "Panamá",
  Jamaica: "Jamaica",
  Honduras: "Honduras",
  "El Salvador": "El Salvador",
  Guatemala: "Guatemala",
  Haiti: "Haiti",
  "Trinidad and Tobago": "Trinidad e Tobago",
  France: "França",
  Germany: "Alemanha",
  Spain: "Espanha",
  Italy: "Itália",
  England: "Inglaterra",
  Netherlands: "Países Baixos",
  Belgium: "Bélgica",
  Portugal: "Portugal",
  Croatia: "Croácia",
  Switzerland: "Suíça",
  Poland: "Polônia",
  Sweden: "Suécia",
  Denmark: "Dinamarca",
  Austria: "Áustria",
  "Czech Republic": "República Tcheca",
  Czechia: "República Tcheca",
  Ukraine: "Ucrânia",
  Serbia: "Sérvia",
  Wales: "País de Gales",
  Scotland: "Escócia",
  Turkey: "Turquia",
  Türkiye: "Turquia",
  Greece: "Grécia",
  Romania: "Romênia",
  Hungary: "Hungria",
  Slovakia: "Eslováquia",
  Slovenia: "Eslovênia",
  Ireland: "Irlanda",
  "Northern Ireland": "Irlanda do Norte",
  Norway: "Noruega",
  Finland: "Finlândia",
  Morocco: "Marrocos",
  Senegal: "Senegal",
  Ghana: "Gana",
  Nigeria: "Nigeria",
  Cameroon: "Camaroes",
  "Ivory Coast": "Costa do Marfim",
  "Côte d'Ivoire": "Costa do Marfim",
  Egypt: "Egito",
  Tunisia: "Tunísia",
  Algeria: "Argélia",
  "South Africa": "África do Sul",
  Kenya: "Quênia",
  Mali: "Mali",
  Japan: "Japão",
  "Korea Republic": "Coreia do Sul",
  "South Korea": "Coreia do Sul",
  "Korea DPR": "Coreia do Norte",
  China: "China",
  Australia: "Austrália",
  "Saudi Arabia": "Arábia Saudita",
  Iran: "Irã",
  Iraq: "Iraque",
  Qatar: "Catar",
  "United Arab Emirates": "Emirados Árabes Unidos",
  Uzbekistan: "Uzbequistão",
  Jordan: "Jordânia",
  Oman: "Omã",
  Bahrain: "Bahrein",
  India: "Índia",
  Indonesia: "Indonesia",
  Thailand: "Tailândia",
  Vietnam: "Vietnã",
  "New Zealand": "Nova Zelândia",
  Curacao: "Curaçao",
  Curaçao: "Curaçao",
  Suriname: "Suriname",
};

/** Siglas em portugues do Brasil para nomes vindos da football-data.org. */
const TEAM_CODES: Record<string, string> = {
  Brazil: "BRA",
  Argentina: "ARG",
  Uruguay: "URU",
  Colombia: "COL",
  Colômbia: "COL",
  Chile: "CHI",
  Peru: "PER",
  Ecuador: "ECU",
  Equador: "ECU",
  Paraguay: "PAR",
  Paraguai: "PAR",
  Bolivia: "BOL",
  Bolívia: "BOL",
  Venezuela: "VEN",
  Mexico: "MEX",
  México: "MEX",
  "United States": "EUA",
  USA: "EUA",
  Canada: "CAN",
  Canadá: "CAN",
  "Costa Rica": "CRC",
  Panama: "PAN",
  Panamá: "PAN",
  Jamaica: "JAM",
  Honduras: "HON",
  "El Salvador": "SLV",
  Guatemala: "GUA",
  Haiti: "HAI",
  "Trinidad and Tobago": "TRI",
  "Trinidad e Tobago": "TRI",
  France: "FRA",
  Franca: "FRA",
  França: "FRA",
  Germany: "ALE",
  Alemanha: "ALE",
  Spain: "ESP",
  Italy: "ITA",
  Italia: "ITA",
  Itália: "ITA",
  England: "ING",
  Inglaterra: "ING",
  Netherlands: "PBA",
  Holanda: "PBA",
  "Países Baixos": "PBA",
  Belgium: "BEL",
  Belgica: "BEL",
  Bélgica: "BEL",
  Portugal: "POR",
  Croatia: "CRO",
  Croacia: "CRO",
  Croácia: "CRO",
  Switzerland: "SUI",
  Suica: "SUI",
  Suíça: "SUI",
  Poland: "POL",
  Polonia: "POL",
  Polônia: "POL",
  Sweden: "SUE",
  Suecia: "SUE",
  Suécia: "SUE",
  Denmark: "DEN",
  Dinamarca: "DIN",
  Austria: "AUT",
  Áustria: "AUT",
  "Czech Republic": "TCH",
  Czechia: "TCH",
  "Republica Tcheca": "TCH",
  "República Tcheca": "TCH",
  Ukraine: "UCR",
  Ucrania: "UCR",
  Ucrânia: "UCR",
  Serbia: "SER",
  Servia: "SER",
  Sérvia: "SER",
  Wales: "GAL",
  "Pais de Gales": "GAL",
  "País de Gales": "GAL",
  Scotland: "ESC",
  Escocia: "ESC",
  Escócia: "ESC",
  Turkey: "TUR",
  Türkiye: "TUR",
  Turquia: "TUR",
  Greece: "GRE",
  Grecia: "GRE",
  Grécia: "GRE",
  Romania: "ROM",
  Romenia: "ROM",
  Romênia: "ROM",
  Hungary: "HUN",
  Hungria: "HUN",
  Slovakia: "ESQ",
  Eslovaquia: "ESQ",
  Eslováquia: "ESQ",
  Slovenia: "ESL",
  Eslovenia: "ESL",
  Eslovênia: "ESL",
  Ireland: "IRL",
  Irlanda: "IRL",
  "Northern Ireland": "IRN",
  "Irlanda do Norte": "IRN",
  Norway: "NOR",
  Noruega: "NOR",
  Finland: "FIN",
  Finlandia: "FIN",
  Finlândia: "FIN",
  Morocco: "MAR",
  Marrocos: "MAR",
  Senegal: "SEN",
  Ghana: "GAN",
  Gana: "GAN",
  Nigeria: "NGA",
  Cameroon: "CAM",
  Camaroes: "CAM",
  "Ivory Coast": "CMF",
  "Côte d'Ivoire": "CMF",
  "Costa do Marfim": "CMF",
  Egypt: "EGI",
  Egito: "EGI",
  Tunisia: "TUN",
  Tunísia: "TUN",
  Algeria: "ALG",
  Argelia: "ALG",
  Argélia: "ALG",
  "South Africa": "AFS",
  "Africa do Sul": "AFS",
  "África do Sul": "AFS",
  Kenya: "KEN",
  Quenia: "KEN",
  Quênia: "KEN",
  Mali: "MLI",
  Japan: "JAP",
  Japao: "JAP",
  Japão: "JAP",
  "Korea Republic": "CDS",
  "South Korea": "CDS",
  "Coreia do Sul": "CDS",
  "Korea DPR": "CDN",
  "Coreia do Norte": "CDN",
  China: "CHN",
  Australia: "AUS",
  "Saudi Arabia": "ARA",
  "Arabia Saudita": "ARA",
  "Arábia Saudita": "ARA",
  Iran: "IRA",
  Ira: "IRA",
  Irã: "IRA",
  Iraq: "IRQ",
  Iraque: "IRQ",
  Qatar: "CAT",
  Catar: "CAT",
  "United Arab Emirates": "EAU",
  "Emirados Arabes Unidos": "EAU",
  "Emirados Árabes Unidos": "EAU",
  Uzbekistan: "UZB",
  Uzbequistao: "UZB",
  Uzbequistão: "UZB",
  Jordan: "JOR",
  Jordania: "JOR",
  Jordânia: "JOR",
  Oman: "OMA",
  Oma: "OMA",
  Omã: "OMA",
  Bahrain: "BAH",
  Bahrein: "BAH",
  India: "IND",
  Índia: "IND",
  Indonesia: "IDN",
  Thailand: "TAI",
  Tailandia: "TAI",
  Tailândia: "TAI",
  Vietnam: "VIE",
  Vietna: "VIE",
  Vietnã: "VIE",
  "New Zealand": "NZL",
  "Nova Zelandia": "NZL",
  "Nova Zelândia": "NZL",
  Curacao: "CUW",
  Curaçao: "CUW",
  Suriname: "SUR",
};

function lookup<T>(map: Record<string, T>, name: string): T | null {
  const trimmed = name.trim();
  if (map[trimmed]) return map[trimmed];

  const key = Object.keys(map).find(
    (k) => k.toLowerCase() === trimmed.toLowerCase()
  );
  return key ? map[key] : null;
}

export function teamDisplayName(name: string): string {
  const trimmed = name.trim();
  if (!trimmed || trimmed === "A definir") return trimmed || "A definir";
  return lookup(TEAM_NAMES_PT_BR, trimmed) ?? trimmed;
}

export function teamAbbrev(name: string): string {
  const trimmed = name.trim();
  if (!trimmed || trimmed === "A definir") return "—";

  const code = lookup(TEAM_CODES, trimmed) ?? lookup(TEAM_CODES, teamDisplayName(trimmed));
  if (code) return code;

  const letters = trimmed.replace(/[^A-Za-zÀ-ÿ]/g, "");
  if (letters.length >= 3) return letters.slice(0, 3).toUpperCase();
  return trimmed.slice(0, 3).toUpperCase();
}

export function isBrazilTeam(name: string): boolean {
  const n = name.trim().toLowerCase();
  return n === "brazil" || n === "brasil";
}
